state:
  file: etc/openapi-client-generator.state
  additionalFiles:
    - composer.json
    - composer.lock
spec: https://www.miele.com/developer/swagger-ui/m3rdapi.yaml
#spec: m3rdapi.yaml
namespace:
  source: ApiClients\Client\Miele
  test: ApiClients\Tests\Client\Miele
entryPoints:
  call: true
  operations: true
  webHooks: false
destination:
  root: generated-miele
  source: src
  test: tests
templates:
  dir: templates
  variables:
    fullname: Miele
    packageName: miele
schemas:
  allowDuplication: true
  useAliasesForDuplication: true
contentType:
  - ApiClients\Tools\OpenApiClientGenerator\ContentType\Json
  - ApiClients\Tools\OpenApiClientGenerator\ContentType\Raw
voter:
  listOperation:
    - ApiClients\Tools\OpenApiClientGenerator\Voter\ListOperation\PageAndPerPageInQuery
  streamOperation:
    - ApiClients\Tools\OpenApiClientGenerator\Voter\StreamOperation\DownloadInOperationId

