state:
  file: etc/openapi-client-generator.state
  additionalFiles:
    - composer.json
    - composer.lock
#spec: https://raw.githubusercontent.com/github/rest-api-description/main/descriptions-next/api.github.com/api.github.com.yaml
spec: api.github.com.yaml
entryPoints:
  call: true
  operations: true
  webHooks: true
namespace:
  source: ApiClients\Client\Github
  test: ApiClients\Tests\Client\Github
destination:
  root: generated-github-subsplit
  source: src
  test: tests
templates:
  dir: templates
  variables:
    foo: bar
schemas:
  allowDuplication: true
  useAliasesForDuplication: true
contentType:
  - ApiClients\Tools\OpenApiClientGenerator\ContentType\Json
  - ApiClients\Tools\OpenApiClientGenerator\ContentType\Raw
voter:
  listOperation:
    - ApiClients\Tools\OpenApiClientGenerator\Voter\ListOperation\PageAndPerPageInQuery
  streamOperation:
    - ApiClients\Tools\OpenApiClientGenerator\Voter\StreamOperation\DownloadInOperationId
subSplit:
  subSplitsDestination: clients
  branch: v0.3.x
  targetVersion: ^v0.3@dev
  subSplitConfiguration: etc/config.subsplit-publish.json
  fullName: GitHub {{ section }}
  vendor: api-clients
  sectionGenerator:
    - ApiClients\Tools\OpenApiClientGenerator\SectionGenerator\OperationIdSlash
    - ApiClients\Tools\OpenApiClientGenerator\SectionGenerator\WebHooks
  rootPackage:
    name: github
    repository: git@github.com:php-api-clients/github.git
  sectionPackage:
    name: github-{{ section }}
    repository: git@github.com:php-api-clients/github-{{ section }}.git
