name: Generate and Test Clients
on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'refs/heads/v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
jobs:
  generate-and-test-client:
    name: Continuous Integration (${{ matrix.client }})
    strategy:
      fail-fast: false
      matrix:
        client: ["miele", "one", "subsplit"]
    uses: ./.github/workflows/test-client.yaml
    with:
      name: ${{ matrix.client }}
